{% set name = "pyAesCrypt" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0914f388254c4906aed48d41e892ca950d43184ebe940acfa31a9d0a04ee2a20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - cryptography
    - python

test:
  imports:
    - pyAesCrypt

about:
  home: https://github.com/marcobellaccini/pyAesCrypt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Encrypt and decrypt files and streams in AES Crypt format (version 2)

extra:
  recipe-maintainers:
    - tschoonj
